import { mkdir, writeFile, access } from 'node:fs/promises';
import { join, relative } from 'node:path';

const CONFIG_FILES = ['tuffgal.config.ts', 'tuffgal.config.js'];

const CONFIG_TEMPLATE = `import { defineConfig } from 'tuffgal';

/**
 * Tuffgal config. The full field reference lives at
 * https://github.com/nschneble/tuffgal/blob/main/docs/config.md.
 *
 * Required: \`paths\` and \`baseUrl\`. Everything else is optional with
 * sensible defaults.
 */
export default defineConfig({
  paths: {
    actions: 'tuffgal/actions',
    stories: 'tuffgal/stories',
    baselines: 'tuffgal/baselines',
    report: 'tuffgal/report',
    authState: 'tuffgal/.auth',
  },

  baseUrl: process.env.APP_BASE_URL ?? 'http://localhost:5173',

  // Uncomment if your app makes API calls under a different origin. Used
  // by intercept patterns to scope routes to API traffic.
  // apiHost: 'http://localhost:3000',

  // localStorage keys to persist across stories. Cookie-based apps may
  // leave this empty — cookies always persist via Playwright storage state.
  // storageStatePins: ['session_token'],

  viewport: { width: 1280, height: 800 },
  defaultTimeoutMs: 10_000,
  navigationTimeoutMs: 15_000,
  frozenTime: '2026-01-15T12:00:00.000Z',

  // Database bridge — wire to your reset + fixture functions. Skip the
  // entire block for static sites. See examples/postgres-prisma/ for a
  // working recipe.
  // database: {
  //   reset: async () => { /* truncate + reseed */ },
  //   fixtures: {
  //     'example-rows': async () => { /* idempotent inserts */ },
  //   },
  // },

  // Dev-server bridge. Used by \`--manage-servers\` and \`tuffgal supervise\`.
  // Omit when you run servers yourself.
  // devServers: {
  //   command: 'npm run dev:test',
  //   healthCheck: [
  //     { url: 'http://localhost:3000', timeoutMs: 120_000 },
  //     { url: 'http://localhost:5173', timeoutMs: 120_000 },
  //   ],
  // },
});
`;

const GITKEEP_SUBDIRECTORIES = [
  'tuffgal/actions',
  'tuffgal/stories',
  'tuffgal/baselines',
];

const REPORT_GITIGNORE = `# Generated by Tuffgal — do not commit.
.auth/
report/
`;

export interface InitOptions {
  cwd: string;
}

/**
 * Scaffolds a starter Tuffgal layout in the given directory:
 *   - tuffgal.config.ts        (commented template)
 *   - tuffgal/actions/.gitkeep
 *   - tuffgal/stories/.gitkeep
 *   - tuffgal/baselines/.gitkeep
 *   - tuffgal/.gitignore       (ignores .auth/ and report/)
 *
 * Refuses to overwrite an existing tuffgal.config.{ts,js}. Existing
 * scaffolded directories are left alone — a second \`init\` is safe to run
 * after manually deleting just the config.
 */
export async function init(options: InitOptions): Promise<void> {
  const { cwd } = options;

  for (const candidate of CONFIG_FILES) {
    if (await pathExists(join(cwd, candidate))) {
      throw new Error(
        `${candidate} already exists at ${cwd}. Refusing to overwrite. ` +
          `Delete it manually if you want to start over.`,
      );
    }
  }

  const configPath = join(cwd, 'tuffgal.config.ts');
  await writeFile(configPath, CONFIG_TEMPLATE, 'utf8');
  process.stdout.write(
    `Wrote ${relative(cwd, configPath) || 'tuffgal.config.ts'}\n`,
  );

  for (const subdirectory of GITKEEP_SUBDIRECTORIES) {
    const absolute = join(cwd, subdirectory);
    await mkdir(absolute, { recursive: true });
    const gitkeep = join(absolute, '.gitkeep');
    if (!(await pathExists(gitkeep))) {
      await writeFile(gitkeep, '', 'utf8');
      process.stdout.write(`Wrote ${relative(cwd, gitkeep)}\n`);
    }
  }

  const gitignorePath = join(cwd, 'tuffgal', '.gitignore');
  if (!(await pathExists(gitignorePath))) {
    await writeFile(gitignorePath, REPORT_GITIGNORE, 'utf8');
    process.stdout.write(`Wrote ${relative(cwd, gitignorePath)}\n`);
  }

  process.stdout.write(
    [
      '',
      'Tuffgal scaffold ready. Next steps:',
      '  1. Edit tuffgal.config.ts to point at your dev server.',
      '  2. Write your first action under tuffgal/actions/.',
      '  3. Write your first story under tuffgal/stories/.',
      '  4. Run `npx tuffgal run` to capture baselines.',
      '',
    ].join('\n'),
  );
}

async function pathExists(absolute: string): Promise<boolean> {
  try {
    await access(absolute);
    return true;
  } catch {
    return false;
  }
}
